language: java
env:
  - PLAY_VERSION=2.0.4
before_install: 
  - mysql --user=root < conf/dbinit.sql
  - wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
  - export PLAY=`pwd`/play-${PLAY_VERSION}
  - export PATH=${PATH}:PLAY
  - mysql --user=root -e 'use WHATDataWarehouse; show tables; select * from mysql.user;'

script: play-${PLAY_VERSION}/play test
notifications:
  irc:
    channels:
      - "irc.freenode.org##kit"
  email: false
  
