language: java
env:
  - PLAY_VERSION=2.0.4
before_script: 
  - mysql --user=root < conf/dbinit.sql
  - wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications:
  irc:
    channels:
      - "irc.freenode.org##kit"
  email: false
  
